FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
     libxml2-dev \
     libxslt-dev \
     && rm -rf /var/lib/apt/lists/*
 
 COPY requirements-converter.txt .
 RUN pip install --no-cache-dir -r requirements-converter.txt
 
 COPY csv_to_xml_converter.py .

 CMD ["python", "csv_to_xml_converter.py"]